### ISSUE TITLE
Request for latest binary version

### ISSUE THREAD

**Issue by kubrick06010** [Dalboz/textual_binary#1]
@wodim atender

**Comment by wodim** [comment]
https://blog.vortigaunt.net/how-to-compile-textual-in-2018/

91ee677 (última de mayo) pero no tengo ganas de subirlo

**Comment by kubrick06010** [comment]
![screen shot 2018-08-17 at 8 36 57 p m](https://user-images.githubusercontent.com/370368/44293875-8ca3bf80-a25d-11e8-89bf-ec17870ad3d3.png)

**Comment by wodim** [comment]
Es un hackintosh?

**Comment by wodim** [comment]
¿Por qué me has bloqueado en Telegram, inútil?

**Comment by kubrick06010** [comment]
lol bazofia no sabía que eras tu!
